-- Drop table

-- DROP TABLE USUARIO;

CREATE TABLE USUARIO (
	I_USUARIO INTEGER NOT NULL AUTO_INCREMENT,
	NLOGIN VARCHAR(30) NOT NULL,
	SENHA VARCHAR(255) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100),
	ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
	PERFIL VARCHAR(50) DEFAULT 'OPERADOR' NOT NULL,
	CONSTRAINT USUARIO_PK PRIMARY KEY (I_USUARIO)
);

CREATE UNIQUE INDEX USUARIO_NLOGIN_IDX ON USUARIO (NLOGIN);
CREATE UNIQUE INDEX USUARIO_EMAIL_IDX ON USUARIO (EMAIL);

-- Drop table

-- DROP TABLE CONTA;

CREATE TABLE CONTA (
	I_CONTA INTEGER NOT NULL AUTO_INCREMENT,
	NOME_CONTA VARCHAR(50) NOT NULL,
	SALDO_INICIAL NUMERIC DEFAULT 0 NOT NULL,
	SALDO_ATUAL NUMERIC DEFAULT 0 NOT NULL,
	ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
	CONSTRAINT CONTA_PK PRIMARY KEY (I_CONTA)
);


-- Drop table

-- DROP TABLE CATEGORIA;

CREATE TABLE CATEGORIA (
	I_CATEGORIA INTEGER NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	CLASSIFICACAO VARCHAR(20) NOT NULL,
	ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
	CONSTRAINT CATEGORIA_PK PRIMARY KEY (I_CATEGORIA)
);

-- Drop table

-- DROP TABLE TIPO;

CREATE TABLE TIPO (
	I_TIPO INTEGER NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	CLASSIFICACAO VARCHAR(20) NOT NULL,
	ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
	CONSTRAINT TIPO_PK PRIMARY KEY (I_TIPO)
);



-- Drop table

-- DROP TABLE COMPETENCIA;

CREATE TABLE COMPETENCIA (
	I_COMPETENCIA INTEGER NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	ABREVIACAO VARCHAR(8) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE NOT NULL,
	CONSTRAINT COMPETENCIA_PK PRIMARY KEY (I_COMPETENCIA)
);


-- Drop table

-- DROP TABLE DESPESA;

CREATE TABLE DESPESA (
	I_DESPESA INTEGER NOT NULL AUTO_INCREMENT,
	I_CONTA INTEGER NOT NULL,
	I_CATEGORIA INTEGER NOT NULL,
	I_COMPETENCIA INTEGER NOT NULL,
	MODO VARCHAR(20) NOT NULL,
	QUANTIDADE_PARCELAS INTEGER DEFAULT 1 NOT NULL,
	PARCELA_ATUAL INTEGER NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	VALOR NUMERIC DEFAULT 0 NOT NULL,
	VENCIMENTO DATE NOT NULL,
	PAGAMENTO DATE,
	PAGO BOOLEAN DEFAULT FALSE NOT NULL,
	SIMULADO BOOLEAN DEFAULT FALSE NOT NULL,
	I_TIPO INTEGER NOT NULL,
	CONSTRAINT DESPESA_PK PRIMARY KEY (I_DESPESA),
	CONSTRAINT DESPESA_FK_CONTA FOREIGN KEY (I_CONTA) REFERENCES CONTA(I_CONTA),
	CONSTRAINT DESPESA_FK_CATEGORIA FOREIGN KEY (I_CATEGORIA) REFERENCES CATEGORIA(I_CATEGORIA),
	CONSTRAINT DESPESA_FK_COMPETENCIA FOREIGN KEY (I_COMPETENCIA) REFERENCES COMPETENCIA(I_COMPETENCIA),
	CONSTRAINT DESPESA_FK_TIPO FOREIGN KEY (I_TIPO) REFERENCES TIPO(I_TIPO)
);


-- Drop table

-- DROP TABLE RECEITA;

CREATE TABLE RECEITA (
	I_RECEITA INTEGER NOT NULL AUTO_INCREMENT,
	I_CONTA INTEGER NOT NULL,
	I_CATEGORIA INTEGER NOT NULL,
	I_COMPETENCIA INTEGER NOT NULL,
	MODO VARCHAR(20) NOT NULL,
	QUANTIDADE_PARCELAS INTEGER DEFAULT 1 NOT NULL,
	PARCELA_ATUAL INTEGER NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	VALOR NUMERIC DEFAULT 0 NOT NULL,
	VENCIMENTO DATE NOT NULL,
	RECEBIMENTO DATE,
	RECEBIDO BOOLEAN DEFAULT FALSE NOT NULL,
	SIMULADO BOOLEAN DEFAULT FALSE NOT NULL,
	I_TIPO INTEGER NOT NULL,
	CONSTRAINT RECEITA_PK PRIMARY KEY (I_RECEITA),
	CONSTRAINT RECEITA_FK_CONTA FOREIGN KEY (I_CONTA) REFERENCES CONTA(I_CONTA),
	CONSTRAINT RECEITA_FK_CATEGORIA FOREIGN KEY (I_CATEGORIA) REFERENCES CATEGORIA(I_CATEGORIA),
	CONSTRAINT RECEITA_FK_TIPO FOREIGN KEY (I_TIPO) REFERENCES TIPO(I_TIPO),
	CONSTRAINT RECEITA_FK_COMPETENCIA FOREIGN KEY (I_COMPETENCIA) REFERENCES COMPETENCIA(I_COMPETENCIA)
);


-- Drop table

-- DROP TABLE SALDO;

CREATE TABLE SALDO (
	I_SALDO INTEGER NOT NULL AUTO_INCREMENT,
	I_CONTA INTEGER NOT NULL,
	I_COMPETENCIA INTEGER NOT NULL,
	VALOR_PREVISTO NUMERIC DEFAULT 0 NOT NULL,
	VALOR_ATUAL NUMERIC DEFAULT 0 NOT NULL,
	ENCERRADO BOOLEAN DEFAULT FALSE NOT NULL,
	CONSTRAINT SALDO_PK PRIMARY KEY (I_SALDO),
	CONSTRAINT SALDO_FK_CONTA FOREIGN KEY (I_CONTA) REFERENCES CONTA(I_CONTA),
	CONSTRAINT SALDO_FK_COMPETENCIA FOREIGN KEY (I_COMPETENCIA) REFERENCES COMPETENCIA(I_COMPETENCIA)
);
